Name:           ros-jade-naoqi-bridge-msgs
Version:        0.0.6
Release:        0%{?dist}
Summary:        ROS naoqi_bridge_msgs package

Group:          Development/Libraries
License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-actionlib-msgs
Requires:       ros-jade-genmsg
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-message-runtime
Requires:       ros-jade-nav-msgs
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-trajectory-msgs
BuildRequires:  ros-jade-actionlib-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-genmsg
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-nav-msgs
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-trajectory-msgs
Conflicts:      ros-jade-naoqi-msgs
Obsoletes:      ros-jade-naoqi-msgs

%description
The naoqi_bridge_msgs package provides custom messages for running Aldebaran's
robot such as NAO and Pepper. See the packages nao_robot and pepper_robot for
details.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Nov 08 2016 Karsten Knese <karsten.knese@gmail.com> - 0.0.6-0
- Autogenerated by Bloom

* Sun Nov 15 2015 Karsten Knese <karsten.knese@gmail.com> - 0.0.5-0
- Autogenerated by Bloom

* Wed Aug 26 2015 Karsten Knese <karsten.knese@gmail.com> - 0.0.4-0
- Autogenerated by Bloom

* Thu Jul 30 2015 Karsten Knese <karsten.knese@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

* Wed Jun 10 2015 kknese <kknese@todo.todo> - 0.0.2-0
- Autogenerated by Bloom

* Wed May 20 2015 kknese <kknese@todo.todo> - 0.0.1-0
- Autogenerated by Bloom

